// 全部 65 关元数据 · 自动生成,改请重跑
// 系列顺序:T(教学) → C(概念) → X(综合) → M(模考) → D/Y/E/F/G(后续幕专属)
module.exports = {
  act1: [
    { id: "T1", title: "醒来的婉婉", concept: "方向指令" },
    { id: "T2", title: "送早餐", concept: "功能指令·捡起和放下" },
    { id: "T3", title: "彩色信号灯", concept: "颜色指令" },
    { id: "T4", title: "图书馆借书证", concept: "凭证指令" },
    { id: "T5", title: "重复浇花", concept: "逻辑指令·重复" },
    { id: "C1", title: "被偷改的购物清单", security: "指令注入", concept: "指令注入" },
    { id: "C2", title: "红钥匙不见了", security: "凭证窃取", concept: "凭证窃取" },
    { id: "C3", title: "会传话的邮筒", security: "中间人攻击", concept: "中间人攻击" },
  ],
  act2: [
    { id: "C4", title: "假扮的水电工", security: "社会工程学", concept: "社会工程学" },
    { id: "C5", title: "后门里的图书馆", security: "越权访问", concept: "越权访问" },
    { id: "C6", title: "蓝色的危险", security: "AI 越狱", concept: "AI 越狱" },
    { id: "C7", title: "冲进面馆的熊孩子", security: "DoS 洪水", concept: "DoS 洪水" },
    { id: "C8", title: "不告诉答案的 NPC", security: "信息推断", concept: "信息推断" },
    { id: "C9", title: "妈妈的 100 块", security: "时序攻击", concept: "时序攻击" },
    { id: "X1", title: "森林迷路小队", concept: "综合 · 注入+中间人" },
    { id: "X2", title: "工厂大逃亡", concept: "综合 · 社工+越权" },
    { id: "X3", title: "沙漠追影", concept: "综合 · DoS+时序" },
  ],
  act3: [
    { id: "X4", title: "指令塔一层·大堂", concept: "塔防 · 注入修复" },
    { id: "X5", title: "指令塔 50 层", concept: "塔防 · 凭证+越权+颜色" },
    { id: "X6", title: "指令塔 99 层", concept: "总决战 · 综合所有" },
    { id: "M1", title: "模考一 · 基础", concept: "模考 · 基础指令" },
    { id: "M2", title: "模考二 · 概念", concept: "模考 · 九类概念" },
    { id: "M3", title: "模考三 · 实战", concept: "模考 · 综合实战" },
  ],
  act4: [
    { id: "M4", title: "模考四 · 实战", concept: "模考 · 进阶实战" },
    { id: "D1", title: "奶奶的生日密码", security: "弱口令", concept: "弱口令" },
    { id: "D2", title: "一万次每秒", security: "暴力破解", concept: "暴力破解" },
    { id: "D3", title: "会说谎的魔盒", security: "逆向工程", concept: "逆向工程" },
    { id: "D4", title: "整个书架都不见了", security: "拖库", concept: "拖库 / 信息泄露" },
    { id: "D5", title: "带字条的礼物", security: "CSRF", concept: "CSRF · 跨站请求伪造" },
    { id: "D6", title: "小天的假面", security: "提示词绕过", concept: "AI 提示词绕过" },
    { id: "D7", title: "凯撒的情书", security: "凯撒密码", concept: "密码学(凯撒)" },
    { id: "D8", title: "画里有话", security: "隐写", concept: "隐写术" },
    { id: "Y1", title: "银行联防战", concept: "综合 · 弱口令 + CSRF" },
    { id: "Y2", title: "拆解暗码社密室", concept: "综合 · 逆向 + 密码学" },
    { id: "Y3", title: "星野站决战", concept: "总决战 · 综合所有" },
  ],
  act5: [
    { id: "E1", title: "开学第一天", security: "第五幕介绍", concept: "新规则 · 过渡" },
    { id: "E2", title: "消失的提示", security: "弱口令", concept: "弱口令(无线索)" },
    { id: "E3", title: "门口的大胡子", security: "社工辨识", concept: "社工辨识" },
    { id: "E4", title: "循环的快递员", security: "重放攻击", concept: "重放攻击" },
    { id: "E5", title: "字里藏箭", security: "注入的位置问题", concept: "注入(位置)" },
    { id: "E6", title: "移位情书", security: "凯撒密码", concept: "凯撒密码(字母)" },
    { id: "E7", title: "前端的贴纸", security: "前后端校验", concept: "前后端分离" },
    { id: "E8", title: "会传染的小怪", security: "病毒", concept: "病毒清理" },
    { id: "E9", title: "藏在好物里的坏", security: "木马", concept: "木马" },
    { id: "E10", title: "双重关卡", security: "多层攻击", concept: "综合:前后端 + 注入" },
    { id: "E11", title: "循环的影子", security: "观察 + 解密", concept: "综合:重放 + 密码学" },
    { id: "E12", title: "扑灭最后一簇", security: "综合防御", concept: "BOSS:综合所有" },
  ],
  act6: [
    { id: "F1", title: "红灯还是绿灯", security: "条件判断", concept: "条件判断 · 看信号" },
    { id: "F2", title: "雨天带伞", security: "条件判断", concept: "条件判断 · 看状态" },
    { id: "F3", title: "编故事的 AI", security: "AI 幻觉", concept: "AI 幻觉" },
    { id: "F4", title: "假的链接", security: "钓鱼链接", concept: "钓鱼网站" },
    { id: "F6", title: "两道锁", security: "二次验证", concept: "二次验证" },
    { id: "F7", title: "聪明的门卫", security: "条件判断 · 进阶", concept: "条件判断 · 看身份" },
  ],
  act7: [
    { id: "G1", title: "大邮筒", security: "公钥邮筒", concept: "大家都能投,只有钥匙能开" },
    { id: "G2", title: "我的印章", security: "印章签名", concept: "我的印,别人仿不出" },
    { id: "G3", title: "没破封的盒子", security: "封条 / 完整性", concept: "封条破了,有人动过" },
    { id: "G4", title: "信被换了", security: "签名 + 封条 综合", concept: "印对 + 封好,才能信" },
    { id: "G5", title: "装病的快递员", security: "社工辨识", concept: "陌生人套近乎要警惕" },
    { id: "G6", title: "弹窗的真假", security: "钓鱼弹窗", concept: "屏幕上跳的窗子,有真有假" },
    { id: "G7", title: "加塞的客人", security: "注入位置", concept: "插队 = 把指令塞错位置" },
    { id: "G8", title: "多嘴的小猫", security: "隐私", concept: "什么能告诉陌生人,什么不能" },
    { id: "G9", title: "病毒来了", security: "病毒清理(进阶)", concept: "病毒会动,要主动清" },
    { id: "G10", title: "改成绿灯", security: "条件变化", concept: "条件可以改" },
    { id: "G11", title: "加密的快递", security: "三件套综合", concept: "三件套连用" },
    { id: "G12", title: "钥匙之战", security: "综合防御", concept: "BOSS · 全部用上" },
  ],
};